language: node_js
node_js:
  - '12'
disty: trusty
services:
  - mongodb
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/admin/node_modules
    - client/website/node_modules
install:
  - npm install
  - npm run install-client-website
  - npm run build-client-website
scripts:
  - nohup npm run ci &
  - sleep 3
  - npm run test-ci
